on: [push]

jobs:
  update_wakatime_image:
    runs-on: ubuntu-latest
    name: Save wakatime stats to file
    steps:
      # To use this repository's private action, you musWt check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Save my WakaTime stats to my repo
        uses: ./ # Uses an action in the root directory
        id: wakatime
        with:
          url: 'https://minituff-github-readme-stats.vercel.app/api/wakatime?username=minituffFAKE&langs_count=18&layout=compact&custom_title=My%20Code%20Stats'
          imagePath: 'media/test.svg'
          deleteOnFail: false
          requiredContentType: 'image/svg+xml; charset=utf-8'
      # If you do not commit the changes, then the action does not work
      - name: "Commit changes if necessary"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updating media/test.svg
  