on: [push]

jobs:
  update_wakatime_image:
    runs-on: ubuntu-latest
    name: Save wakatime stats to file
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Save my WakaTime stats to my repo
        uses: Minituff/save-image@dev
        id: wakatime
        with:
          url: 'https://minituff-github-readme-stats.vercel.app/api/wakatime?username=minituff&langs_count=18&layout=compact&custom_title=My%20Code%20Stats'
          imagePath: 'media/wakatime-data.svg'
          requiredContentType: 'image/svg+xml; charset=utf-8'

      # If you do not commit the changes, then the action does not work
      - name: "Commit changes if necessary"
        uses: stefanzweifel/git-auto-commit-action@v4.13.1
        with:
          commit_message: Updating media/wakatime-data.svg
  
